[project]
name = "anakin2"
version = "0.1.0"
description = "Kill all the orphans of a child process"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
bindings = "bin"
